[user]
name = "Goran Peretin"
email = "goran.peretin@gmail.com"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
l = ["log", "-r", "all()", "-n", "10"]

[ui]
default-command = "status"
pager = ["delta", "--side-by-side"]
editor = "vim"

[ui.diff]
format = "git"

[revsets]
log = "latest(::@ | trunk(), 10)"

[git]
fetch = "*"
