[user]
name = "Goran Peretin"
email = "goran.peretin@gmail.com"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"];

[ui]
default-command = "status"
pager = "delta"
